### ISSUE TITLE
Angular Jenkins setup: No binary fro ChromeHeadless browser on your platform

### ISSUE THREAD

**Issue by bartvanderwal** [ddoa/docker-jenkins-slaves#28]
Student (groep Borg)

>Ik loop tegen een probleem aan met het opzetten van Jenkins voor de frontend (https://jenkins.aimsites.nl/job/OOSE%20Borg%20Front-end). Het uitvoeren van de unit tests vereist een browser maar die wordt niet gevonden. Ik heb precies dezelfde configuratie overgenomen als die van het test project (https://jenkins.aimsites.nl/job/OOSE-Jenkins-Slave-Angular-Test/configure) en daar werkt het wel. Enig idee wat ik verkeerd doe?
>![image](https://user-images.githubusercontent.com/3029472/171482476-78e1901d-adb5-4695-9970-e34bfe906e2a.png)

## Mogelijke FIX
Suggestie Jaap Papavoine via berichtje in Teams:

>[...] Chrome installeren in die docker container is niet super makkelijk. Maar er is een chromium npm packge die je kunt gebruiken. Je moet dan dit in een sh scriptje runnen als deel van de Jenkins job:
>```bash
>npm install chromium
>export CHROME_BIN=./node_modules/chromium/lib/chromium/chrome-linux/chrome
>```
>En vervolgens een chromeheadless gebruiken met een extra optie ... in de `karma.config.js`:
>
>```JSON
>  browsers: ['ChromeHeadlessNoSandbox'],
>  customLaunchers: {​​​​​​​
>    ChromeHeadlessNoSandbox: {​​​​​​​
>      base: 'ChromeHeadless',
>      flags: ['--no-sandbox']
>    }​​​​​ ​​
>  }​​​​​​​,
>```

## Alternatief: Chromium in Docker image
Ik denk dat in de Docker file `debian:11` i.p.v. debian:latest gebruiken als base imge wat meer stabiliteit geeft.

Dan hoef je Chromium niet telkens opnieuw te installeren tijdens runnen job.

In Debian 11 lijkt een simpele `apt install chromium `wel direct te werken, [deze blog](https://vitux.com/debian-chromium-browser/) volgend. Gat stuk makkelijker dan Chrome (vandaar dat het in npm ook kan denk ik).

Maar als je je dat in Dockerfile toevoegt ergens tussen de andere apt install's. En dan in je Jenkins setup deze environment variabele 

```bash
CHROME_BIN=/usr/bin/chromium-browser
```

Volgens deze [StackOverflow post](https://stackoverflow.com/questions/16873001/karma-tests-on-chromium) (maar bij even testen heet deze CHROME_BIN=/usr/bin/chromium, dus zonder '-browser'.

Misschien meteen VOOR chromium ook toevoegen

```bash
apt-get install dialog
```

Vanwege melding die ik ergens langs zag komen bij install
>no usable dialog-like program is installed, so the dialog based frontend cannot be used.

**Comment by rodymiddelkoop** [comment]
Jenkins job aangepast:
* npm install puppeteer 
* CHROME_BIN gezet
* -- watch=false achter de ng test, anders sluit Chrome/Chromium niet af
